### ISSUE TITLE
fdsp_digital.lib contains unresolved merge conflicts

### ISSUE THREAD

**Issue by maxanier** [freeDSP/freeDSP-KiCadLibrary#1]
Hello,

KiCad complains about a undefined draw command in fdsp_digital.lib.
Apparently the current version contains some remains of a failed/incomplete git merge (commit 0a81bfb18288ba0d56fb3f71037e2085f3f75bbd by @ssMMnn)
https://github.com/freeDSP/freeDSP-KiCadLibrary/blob/0a81bfb18288ba0d56fb3f71037e2085f3f75bbd/Symbol/fdsp_digital.lib#L54.

I would be grateful if someone could solve this, as I have little experience with KiCad yet and don't know how to fix it myself.

Thanks :)

**Comment by ssMMnn** [comment]
Hello,

the issue is fixed! It was indeed a failed merge of two branches.

greetings | ssMMnn

Am 01.05.2017 um 14:37 schrieb Max Becker:
